# This file was auto-generated by Fern from our API Definition.

import enum


class VitableConnectEnvironment(enum.Enum):
    PRODUCTION = "https://api.vitablehealth.com"
    UAT = "https://api.uat.vitablehealth.com"
