# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.household_members_response import HouseholdMembersResponse
from ..types.limit import Limit
from ..types.member_dependents_response import MemberDependentsResponse
from ..types.member_digital_benefit_cards_response import MemberDigitalBenefitCardsResponse
from ..types.member_employments_response import MemberEmploymentsResponse
from ..types.member_enrollments_response import MemberEnrollmentsResponse
from ..types.member_id import MemberId
from ..types.member_list_item import MemberListItem
from ..types.member_list_response import MemberListResponse
from ..types.member_qualifying_life_event import MemberQualifyingLifeEvent
from ..types.member_qualifying_life_event_list_response import MemberQualifyingLifeEventListResponse
from ..types.member_response import MemberResponse
from ..types.member_search import MemberSearch
from ..types.page import Page
from ..types.status import Status
from .raw_client import AsyncRawMembersClient, RawMembersClient


class MembersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMembersClient
        """
        return self._raw_client

    def get(self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None) -> MemberResponse:
        """
        Retrieves a member's profile by ID — identity, demographics, address, contact details, tobacco status, and profile status. Access is scoped to the authenticated principal; a member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId
            Unique member identifier (mbr_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.members.get(
            member_id="mbr_abc123def456",
        )
        """
        _response = self._raw_client.get(member_id, request_options=request_options)
        return _response.data

    def list_dependents(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberDependentsResponse:
        """
        Lists a member's active legal dependents — name, relationship, date of birth, age, and sex at birth. Access is scoped to the authenticated principal; a member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberDependentsResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.members.list_dependents(
            member_id="mbr_abc123def456",
        )
        """
        _response = self._raw_client.list_dependents(member_id, request_options=request_options)
        return _response.data

    def list_employments(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberEmploymentsResponse:
        """
        Lists a member's employment across every employer — the same employee record shape as the employer's employees list, plus the employer name. For an organization caller the rows are scoped to companies in that organization's book; a member (self/household) or Vitable Admin sees all employments. A member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberEmploymentsResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.members.list_employments(
            member_id="mbr_abc123def456",
        )
        """
        _response = self._raw_client.list_employments(member_id, request_options=request_options)
        return _response.data

    def list_enrollments(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberEnrollmentsResponse:
        """
        Lists a member's benefit enrollments across every employer — benefit type and product, employer, carrier, plan, tier, employee deduction, employer contribution and total premium, the individual enrollment coverage boundary (`coverage_end`), the separate pre-effective cancellation boundary (`cancelled_date`), and the distinct benefit plan-year boundary (`plan_year_coverage_end`) used to determine whether the plan year itself has ended, the date the enrollment record was created (`issued_date`, the value Ops labels Issued on, reported for every row whatever the member answered), the window the member could answer in -- which never opens before the enrollment was issued, so a row issued mid-open-enrollment starts its window on its issue date -- whether a qualifying life event would currently be required for reissue under the product/open-enrollment rule, enrollment/open-enrollment window, and two statuses: `election_status` (what the member answered) and `policy_status` (what became of their coverage, null unless they enrolled). Every row includes a stable enrollment ID and the exact employer and benefit plan-year IDs used to fetch that row's plan-year detail. The full list is returned across all states so the client derives active plans (effective and upcoming) and the enrollment history from those per-row statuses. For an organization caller the rows are scoped to companies in that organization's book; a member (self/household) or Vitable Admin sees all enrollments. A member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberEnrollmentsResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.members.list_enrollments(
            member_id="mbr_abc123def456",
        )
        """
        _response = self._raw_client.list_enrollments(member_id, request_options=request_options)
        return _response.data

    def get_household(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HouseholdMembersResponse:
        """
        Lists a member's household as a per-participant table — the account holder plus each active household member, with name, relationship, member type, date of birth, and household-admin flag. Access is scoped to the authenticated principal; a member not visible to the caller (or with no household) returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HouseholdMembersResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.members.get_household(
            member_id="mbr_abc123def456",
        )
        """
        _response = self._raw_client.get_household(member_id, request_options=request_options)
        return _response.data

    def list_id_cards(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberDigitalBenefitCardsResponse:
        """
        Lists a member's benefit ID cards — card type (medical, dental, vision, or rx), employer, plan, provider network, claims payer, carrier contact details, and the disclaimers printed on the card. Medical, dental and vision cards come from the member's active digital benefit cards; the rx card from the member's Ventegra pharmacy benefit (omitted when the member has no free-medication coverage), which carries no plan, network, or carrier details. Access is scoped to the authenticated principal, and an organization caller sees only cards from employers in its book; a member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberDigitalBenefitCardsResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.members.list_id_cards(
            member_id="mbr_abc123def456",
        )
        """
        _response = self._raw_client.list_id_cards(member_id, request_options=request_options)
        return _response.data

    def list_qualifying_life_events(
        self,
        member_id: MemberId,
        *,
        limit: typing.Optional[Limit] = None,
        page: typing.Optional[Page] = None,
        status: typing.Optional[Status] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[MemberQualifyingLifeEvent, MemberQualifyingLifeEventListResponse]:
        """
        Lists a member's qualifying life events, including events already used for another enrollment. Returns all statuses by default; pass the status query param to filter to one (e.g. approved). Events are ordered newest submission first with stable paging. Custom text is present only when submitted and is otherwise null. A member not visible to the caller returns a 404. API keys and unbound access tokens have organization-wide access. Employer-bound tokens require employment at the bound employer, and employee-bound tokens require the exact employee-member relationship. Organization or scope mismatches return a 404 before pagination is validated.

        Parameters
        ----------
        member_id : MemberId
            Unique member identifier (mbr_*)

        limit : typing.Optional[Limit]
            Items per page (default: 20, max: 100)

        page : typing.Optional[Page]
            Page number (default: 1)

        status : typing.Optional[Status]
            Optional. Filter to a single QLE status; omit to return all statuses.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[MemberQualifyingLifeEvent, MemberQualifyingLifeEventListResponse]


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        response = client.members.list_qualifying_life_events(
            member_id="mbr_abc123def456",
            limit=20,
            page=1,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_qualifying_life_events(
            member_id, limit=limit, page=page, status=status, request_options=request_options
        )

    def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page: typing.Optional[Page] = None,
        search: typing.Optional[MemberSearch] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[MemberListItem, MemberListResponse]:
        """
        Retrieves a paginated list of the members in the authenticated organization's book — identity, contact details, and address. The book covers members reached through an employer in the organization's book as well as members of a group it owns. Supports free-text search (name, email, phone number, or exact member id).

        Parameters
        ----------
        limit : typing.Optional[Limit]
            Items per page (default: 20, max: 100)

        page : typing.Optional[Page]
            Page number (default: 1)

        search : typing.Optional[MemberSearch]
            Case-insensitive search across member name, email, and phone number; exact match on member id (prefixed or raw uuid)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[MemberListItem, MemberListResponse]


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        response = client.members.list(
            limit=20,
            page=1,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(limit=limit, page=page, search=search, request_options=request_options)


class AsyncMembersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMembersClient
        """
        return self._raw_client

    async def get(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberResponse:
        """
        Retrieves a member's profile by ID — identity, demographics, address, contact details, tobacco status, and profile status. Access is scoped to the authenticated principal; a member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId
            Unique member identifier (mbr_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.members.get(
                member_id="mbr_abc123def456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(member_id, request_options=request_options)
        return _response.data

    async def list_dependents(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberDependentsResponse:
        """
        Lists a member's active legal dependents — name, relationship, date of birth, age, and sex at birth. Access is scoped to the authenticated principal; a member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberDependentsResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.members.list_dependents(
                member_id="mbr_abc123def456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_dependents(member_id, request_options=request_options)
        return _response.data

    async def list_employments(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberEmploymentsResponse:
        """
        Lists a member's employment across every employer — the same employee record shape as the employer's employees list, plus the employer name. For an organization caller the rows are scoped to companies in that organization's book; a member (self/household) or Vitable Admin sees all employments. A member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberEmploymentsResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.members.list_employments(
                member_id="mbr_abc123def456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_employments(member_id, request_options=request_options)
        return _response.data

    async def list_enrollments(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberEnrollmentsResponse:
        """
        Lists a member's benefit enrollments across every employer — benefit type and product, employer, carrier, plan, tier, employee deduction, employer contribution and total premium, the individual enrollment coverage boundary (`coverage_end`), the separate pre-effective cancellation boundary (`cancelled_date`), and the distinct benefit plan-year boundary (`plan_year_coverage_end`) used to determine whether the plan year itself has ended, the date the enrollment record was created (`issued_date`, the value Ops labels Issued on, reported for every row whatever the member answered), the window the member could answer in -- which never opens before the enrollment was issued, so a row issued mid-open-enrollment starts its window on its issue date -- whether a qualifying life event would currently be required for reissue under the product/open-enrollment rule, enrollment/open-enrollment window, and two statuses: `election_status` (what the member answered) and `policy_status` (what became of their coverage, null unless they enrolled). Every row includes a stable enrollment ID and the exact employer and benefit plan-year IDs used to fetch that row's plan-year detail. The full list is returned across all states so the client derives active plans (effective and upcoming) and the enrollment history from those per-row statuses. For an organization caller the rows are scoped to companies in that organization's book; a member (self/household) or Vitable Admin sees all enrollments. A member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberEnrollmentsResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.members.list_enrollments(
                member_id="mbr_abc123def456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_enrollments(member_id, request_options=request_options)
        return _response.data

    async def get_household(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HouseholdMembersResponse:
        """
        Lists a member's household as a per-participant table — the account holder plus each active household member, with name, relationship, member type, date of birth, and household-admin flag. Access is scoped to the authenticated principal; a member not visible to the caller (or with no household) returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HouseholdMembersResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.members.get_household(
                member_id="mbr_abc123def456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_household(member_id, request_options=request_options)
        return _response.data

    async def list_id_cards(
        self, member_id: MemberId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MemberDigitalBenefitCardsResponse:
        """
        Lists a member's benefit ID cards — card type (medical, dental, vision, or rx), employer, plan, provider network, claims payer, carrier contact details, and the disclaimers printed on the card. Medical, dental and vision cards come from the member's active digital benefit cards; the rx card from the member's Ventegra pharmacy benefit (omitted when the member has no free-medication coverage), which carries no plan, network, or carrier details. Access is scoped to the authenticated principal, and an organization caller sees only cards from employers in its book; a member not visible to the caller returns a 404.

        Parameters
        ----------
        member_id : MemberId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberDigitalBenefitCardsResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.members.list_id_cards(
                member_id="mbr_abc123def456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_id_cards(member_id, request_options=request_options)
        return _response.data

    async def list_qualifying_life_events(
        self,
        member_id: MemberId,
        *,
        limit: typing.Optional[Limit] = None,
        page: typing.Optional[Page] = None,
        status: typing.Optional[Status] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[MemberQualifyingLifeEvent, MemberQualifyingLifeEventListResponse]:
        """
        Lists a member's qualifying life events, including events already used for another enrollment. Returns all statuses by default; pass the status query param to filter to one (e.g. approved). Events are ordered newest submission first with stable paging. Custom text is present only when submitted and is otherwise null. A member not visible to the caller returns a 404. API keys and unbound access tokens have organization-wide access. Employer-bound tokens require employment at the bound employer, and employee-bound tokens require the exact employee-member relationship. Organization or scope mismatches return a 404 before pagination is validated.

        Parameters
        ----------
        member_id : MemberId
            Unique member identifier (mbr_*)

        limit : typing.Optional[Limit]
            Items per page (default: 20, max: 100)

        page : typing.Optional[Page]
            Page number (default: 1)

        status : typing.Optional[Status]
            Optional. Filter to a single QLE status; omit to return all statuses.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[MemberQualifyingLifeEvent, MemberQualifyingLifeEventListResponse]


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.members.list_qualifying_life_events(
                member_id="mbr_abc123def456",
                limit=20,
                page=1,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_qualifying_life_events(
            member_id, limit=limit, page=page, status=status, request_options=request_options
        )

    async def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page: typing.Optional[Page] = None,
        search: typing.Optional[MemberSearch] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[MemberListItem, MemberListResponse]:
        """
        Retrieves a paginated list of the members in the authenticated organization's book — identity, contact details, and address. The book covers members reached through an employer in the organization's book as well as members of a group it owns. Supports free-text search (name, email, phone number, or exact member id).

        Parameters
        ----------
        limit : typing.Optional[Limit]
            Items per page (default: 20, max: 100)

        page : typing.Optional[Page]
            Page number (default: 1)

        search : typing.Optional[MemberSearch]
            Case-insensitive search across member name, email, and phone number; exact match on member id (prefixed or raw uuid)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[MemberListItem, MemberListResponse]


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.members.list(
                limit=20,
                page=1,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(limit=limit, page=page, search=search, request_options=request_options)
