# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.enrollment_id import EnrollmentId
from ..types.enrollment_response import EnrollmentResponse
from ..types.reissue_enrollment_response import ReissueEnrollmentResponse
from .raw_client import AsyncRawEnrollmentsClient, RawEnrollmentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EnrollmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEnrollmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEnrollmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEnrollmentsClient
        """
        return self._raw_client

    def get(
        self, enrollment_id: EnrollmentId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EnrollmentResponse:
        """
        Retrieves a single enrollment: the employee and employer it belongs to, the benefit product, its status, the coverage period, the employee payroll deduction and employer contribution, and the enrolled plan's Summary of Benefits and Coverage document when one is on file. An enrollment the caller cannot reach is indistinguishable from one that does not exist.

        Parameters
        ----------
        enrollment_id : EnrollmentId
            Unique enrollment identifier (enrl_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnrollmentResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.enrollments.get(
            enrollment_id="enrl_AAAAAAAAAAAAAAAAAAAAAQ",
        )
        """
        _response = self._raw_client.get(enrollment_id, request_options=request_options)
        return _response.data

    def reissue(
        self,
        enrollment_id: EnrollmentId,
        *,
        reason: typing.Optional[str] = OMIT,
        ticket_number: typing.Optional[str] = OMIT,
        qualifying_life_event_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ReissueEnrollmentResponse:
        """
        Closes the targeted enrollment and creates a new unanswered enrollment for the same member and plan year. VPC never requires a qualifying life event; other products require an accepted, member-owned event outside open enrollment. User-backed callers must provide a reason; it is optional for organization API-key callers. Tenant mismatches return a non-disclosing 404 before the request body is validated.

        Parameters
        ----------
        enrollment_id : EnrollmentId
            Unique enrollment identifier (enrl_*)

        reason : typing.Optional[str]
            Audit reason for the reissue; required for user-backed callers and optional for long-lived organization API-key callers

        ticket_number : typing.Optional[str]
            Optional support or operational ticket number

        qualifying_life_event_id : typing.Optional[str]
            Accepted member qualifying life event identifier (qle_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReissueEnrollmentResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.enrollments.reissue(
            enrollment_id="enrl_AAAAAAAAAAAAAAAAAAAAAQ",
            reason="Member needs a new election after a qualifying event.",
            ticket_number="BPT-1234",
            qualifying_life_event_id="qle_AAAAAAAAAAAAAAAAAAAAAQ",
        )
        """
        _response = self._raw_client.reissue(
            enrollment_id,
            reason=reason,
            ticket_number=ticket_number,
            qualifying_life_event_id=qualifying_life_event_id,
            request_options=request_options,
        )
        return _response.data

    def terminate(
        self,
        enrollment_id: EnrollmentId,
        *,
        reason: typing.Optional[str] = OMIT,
        ticket_number: typing.Optional[str] = OMIT,
        qualifying_life_event_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Terminates enrolled coverage immediately. An accepted qualifying life event owned by the enrollment member is required unless the plan is VPC or ICHRA. User-backed callers must provide a reason; it is optional for organization API-key callers. API keys may act across the caller organization's book. Tenant mismatches return the same non-disclosing 404 before the request body is validated.

        Parameters
        ----------
        enrollment_id : EnrollmentId
            Unique enrollment identifier (enrl_*)

        reason : typing.Optional[str]
            Audit reason for the termination; required for user-backed callers and optional for long-lived organization API-key callers

        ticket_number : typing.Optional[str]
            Optional support or operational ticket number

        qualifying_life_event_id : typing.Optional[str]
            Accepted member qualifying life event identifier (qle_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.enrollments.terminate(
            enrollment_id="enrl_AAAAAAAAAAAAAAAAAAAAAQ",
            reason="Member requested coverage termination after a qualifying event.",
            ticket_number="BPT-1234",
            qualifying_life_event_id="qle_AAAAAAAAAAAAAAAAAAAAAQ",
        )
        """
        _response = self._raw_client.terminate(
            enrollment_id,
            reason=reason,
            ticket_number=ticket_number,
            qualifying_life_event_id=qualifying_life_event_id,
            request_options=request_options,
        )
        return _response.data


class AsyncEnrollmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEnrollmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEnrollmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEnrollmentsClient
        """
        return self._raw_client

    async def get(
        self, enrollment_id: EnrollmentId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EnrollmentResponse:
        """
        Retrieves a single enrollment: the employee and employer it belongs to, the benefit product, its status, the coverage period, the employee payroll deduction and employer contribution, and the enrolled plan's Summary of Benefits and Coverage document when one is on file. An enrollment the caller cannot reach is indistinguishable from one that does not exist.

        Parameters
        ----------
        enrollment_id : EnrollmentId
            Unique enrollment identifier (enrl_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnrollmentResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.enrollments.get(
                enrollment_id="enrl_AAAAAAAAAAAAAAAAAAAAAQ",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(enrollment_id, request_options=request_options)
        return _response.data

    async def reissue(
        self,
        enrollment_id: EnrollmentId,
        *,
        reason: typing.Optional[str] = OMIT,
        ticket_number: typing.Optional[str] = OMIT,
        qualifying_life_event_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ReissueEnrollmentResponse:
        """
        Closes the targeted enrollment and creates a new unanswered enrollment for the same member and plan year. VPC never requires a qualifying life event; other products require an accepted, member-owned event outside open enrollment. User-backed callers must provide a reason; it is optional for organization API-key callers. Tenant mismatches return a non-disclosing 404 before the request body is validated.

        Parameters
        ----------
        enrollment_id : EnrollmentId
            Unique enrollment identifier (enrl_*)

        reason : typing.Optional[str]
            Audit reason for the reissue; required for user-backed callers and optional for long-lived organization API-key callers

        ticket_number : typing.Optional[str]
            Optional support or operational ticket number

        qualifying_life_event_id : typing.Optional[str]
            Accepted member qualifying life event identifier (qle_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReissueEnrollmentResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.enrollments.reissue(
                enrollment_id="enrl_AAAAAAAAAAAAAAAAAAAAAQ",
                reason="Member needs a new election after a qualifying event.",
                ticket_number="BPT-1234",
                qualifying_life_event_id="qle_AAAAAAAAAAAAAAAAAAAAAQ",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.reissue(
            enrollment_id,
            reason=reason,
            ticket_number=ticket_number,
            qualifying_life_event_id=qualifying_life_event_id,
            request_options=request_options,
        )
        return _response.data

    async def terminate(
        self,
        enrollment_id: EnrollmentId,
        *,
        reason: typing.Optional[str] = OMIT,
        ticket_number: typing.Optional[str] = OMIT,
        qualifying_life_event_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Terminates enrolled coverage immediately. An accepted qualifying life event owned by the enrollment member is required unless the plan is VPC or ICHRA. User-backed callers must provide a reason; it is optional for organization API-key callers. API keys may act across the caller organization's book. Tenant mismatches return the same non-disclosing 404 before the request body is validated.

        Parameters
        ----------
        enrollment_id : EnrollmentId
            Unique enrollment identifier (enrl_*)

        reason : typing.Optional[str]
            Audit reason for the termination; required for user-backed callers and optional for long-lived organization API-key callers

        ticket_number : typing.Optional[str]
            Optional support or operational ticket number

        qualifying_life_event_id : typing.Optional[str]
            Accepted member qualifying life event identifier (qle_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.enrollments.terminate(
                enrollment_id="enrl_AAAAAAAAAAAAAAAAAAAAAQ",
                reason="Member requested coverage termination after a qualifying event.",
                ticket_number="BPT-1234",
                qualifying_life_event_id="qle_AAAAAAAAAAAAAAAAAAAAAQ",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.terminate(
            enrollment_id,
            reason=reason,
            ticket_number=ticket_number,
            qualifying_life_event_id=qualifying_life_event_id,
            request_options=request_options,
        )
        return _response.data
