# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.compensation_type import CompensationType
from ..types.employee_address_input import EmployeeAddressInput
from ..types.employee_class import EmployeeClass
from ..types.employee_id import EmployeeId
from ..types.employee_response import EmployeeResponse
from ..types.enrollment import Enrollment
from ..types.enrollment_list_response import EnrollmentListResponse
from ..types.gender import Gender
from ..types.limit import Limit
from ..types.page import Page
from .raw_client import AsyncRawEmployeesClient, RawEmployeesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EmployeesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEmployeesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEmployeesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEmployeesClient
        """
        return self._raw_client

    def get(
        self, employee_id: EmployeeId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EmployeeResponse:
        """
        Retrieves detailed information for a specific employee by ID. Returns employee details including personal information, employment status, classification and compensation-type effective dates, compensation type, and payroll deductions from the most recent statement period. Deductions reflect a snapshot of the current period and are replaced when a new statement is generated.

        Parameters
        ----------
        employee_id : EmployeeId
            Unique employee identifier (empl_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmployeeResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.employees.get(
            employee_id="empl_abc123def456",
        )
        """
        _response = self._raw_client.get(employee_id, request_options=request_options)
        return _response.data

    def update(
        self,
        employee_id: EmployeeId,
        *,
        effective_date: dt.date,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        gender: typing.Optional[Gender] = OMIT,
        address: typing.Optional[EmployeeAddressInput] = OMIT,
        employee_class: typing.Optional[EmployeeClass] = OMIT,
        start_date: typing.Optional[dt.date] = OMIT,
        compensation_type: typing.Optional[CompensationType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EmployeeResponse:
        """
        Updates employee personal, contact, address, and employment fields. This endpoint currently supports email, phone, gender, address, employee_class, start_date, and compensation_type. effective_date is required and applies to employee_class and compensation_type when those fields are included in the request.

        Parameters
        ----------
        employee_id : EmployeeId
            Unique employee identifier (empl_*)

        effective_date : dt.date
            Past or present date applied to each tracked employment field included in this request

        email : typing.Optional[str]
            Email address

        phone : typing.Optional[str]
            Phone number

        gender : typing.Optional[Gender]
            Gender identity

            * `Male` - Male
            * `Female` - Female
            * `Transgender` - Transgender
            * `Non-binary` - Non-binary
            * `Prefer not to respond` - Prefer not to respond

        address : typing.Optional[EmployeeAddressInput]
            Employee's residential address

        employee_class : typing.Optional[EmployeeClass]
            Employment classification

            * `Full Time` - Full Time
            * `Part Time` - Part Time
            * `Temporary` - Temporary
            * `Intern` - Intern
            * `Seasonal` - Seasonal
            * `Individual Contractor` - Individual Contractor

        start_date : typing.Optional[dt.date]
            Employment start date

        compensation_type : typing.Optional[CompensationType]
            Employee compensation type

            * `Salary` - Salary
            * `Hourly` - Hourly

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmployeeResponse


        Examples
        --------
        import datetime

        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.employees.update(
            employee_id="empl_abc123def456",
            employee_class="Full Time",
            start_date=datetime.date.fromisoformat(
                "2023-01-15",
            ),
            compensation_type="Salary",
            effective_date=datetime.date.fromisoformat(
                "2023-03-01",
            ),
        )
        """
        _response = self._raw_client.update(
            employee_id,
            effective_date=effective_date,
            email=email,
            phone=phone,
            gender=gender,
            address=address,
            employee_class=employee_class,
            start_date=start_date,
            compensation_type=compensation_type,
            request_options=request_options,
        )
        return _response.data

    def list_enrollments(
        self,
        employee_id: EmployeeId,
        *,
        limit: typing.Optional[Limit] = None,
        page: typing.Optional[Page] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Enrollment, EnrollmentListResponse]:
        """
        Retrieves a paginated list of benefit enrollments for an employee.

        Parameters
        ----------
        employee_id : EmployeeId
            Unique employee identifier (empl_*)

        limit : typing.Optional[Limit]
            Items per page (default: 20, max: 100)

        page : typing.Optional[Page]
            Page number (default: 1)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Enrollment, EnrollmentListResponse]


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        response = client.employees.list_enrollments(
            employee_id="empl_abc123def456",
            limit=20,
            page=1,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_enrollments(employee_id, limit=limit, page=page, request_options=request_options)


class AsyncEmployeesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEmployeesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEmployeesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEmployeesClient
        """
        return self._raw_client

    async def get(
        self, employee_id: EmployeeId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EmployeeResponse:
        """
        Retrieves detailed information for a specific employee by ID. Returns employee details including personal information, employment status, classification and compensation-type effective dates, compensation type, and payroll deductions from the most recent statement period. Deductions reflect a snapshot of the current period and are replaced when a new statement is generated.

        Parameters
        ----------
        employee_id : EmployeeId
            Unique employee identifier (empl_*)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmployeeResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.employees.get(
                employee_id="empl_abc123def456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(employee_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        employee_id: EmployeeId,
        *,
        effective_date: dt.date,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        gender: typing.Optional[Gender] = OMIT,
        address: typing.Optional[EmployeeAddressInput] = OMIT,
        employee_class: typing.Optional[EmployeeClass] = OMIT,
        start_date: typing.Optional[dt.date] = OMIT,
        compensation_type: typing.Optional[CompensationType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EmployeeResponse:
        """
        Updates employee personal, contact, address, and employment fields. This endpoint currently supports email, phone, gender, address, employee_class, start_date, and compensation_type. effective_date is required and applies to employee_class and compensation_type when those fields are included in the request.

        Parameters
        ----------
        employee_id : EmployeeId
            Unique employee identifier (empl_*)

        effective_date : dt.date
            Past or present date applied to each tracked employment field included in this request

        email : typing.Optional[str]
            Email address

        phone : typing.Optional[str]
            Phone number

        gender : typing.Optional[Gender]
            Gender identity

            * `Male` - Male
            * `Female` - Female
            * `Transgender` - Transgender
            * `Non-binary` - Non-binary
            * `Prefer not to respond` - Prefer not to respond

        address : typing.Optional[EmployeeAddressInput]
            Employee's residential address

        employee_class : typing.Optional[EmployeeClass]
            Employment classification

            * `Full Time` - Full Time
            * `Part Time` - Part Time
            * `Temporary` - Temporary
            * `Intern` - Intern
            * `Seasonal` - Seasonal
            * `Individual Contractor` - Individual Contractor

        start_date : typing.Optional[dt.date]
            Employment start date

        compensation_type : typing.Optional[CompensationType]
            Employee compensation type

            * `Salary` - Salary
            * `Hourly` - Hourly

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmployeeResponse


        Examples
        --------
        import asyncio
        import datetime

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.employees.update(
                employee_id="empl_abc123def456",
                employee_class="Full Time",
                start_date=datetime.date.fromisoformat(
                    "2023-01-15",
                ),
                compensation_type="Salary",
                effective_date=datetime.date.fromisoformat(
                    "2023-03-01",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            employee_id,
            effective_date=effective_date,
            email=email,
            phone=phone,
            gender=gender,
            address=address,
            employee_class=employee_class,
            start_date=start_date,
            compensation_type=compensation_type,
            request_options=request_options,
        )
        return _response.data

    async def list_enrollments(
        self,
        employee_id: EmployeeId,
        *,
        limit: typing.Optional[Limit] = None,
        page: typing.Optional[Page] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Enrollment, EnrollmentListResponse]:
        """
        Retrieves a paginated list of benefit enrollments for an employee.

        Parameters
        ----------
        employee_id : EmployeeId
            Unique employee identifier (empl_*)

        limit : typing.Optional[Limit]
            Items per page (default: 20, max: 100)

        page : typing.Optional[Page]
            Page number (default: 1)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Enrollment, EnrollmentListResponse]


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.employees.list_enrollments(
                employee_id="empl_abc123def456",
                limit=20,
                page=1,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_enrollments(
            employee_id, limit=limit, page=page, request_options=request_options
        )
