# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.organization import Organization
from ..types.organization_type import OrganizationType
from ..types.organizations_list_response import OrganizationsListResponse
from .raw_client import AsyncRawOrganizationsClient, RawOrganizationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrganizationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrganizationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrganizationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrganizationsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationsListResponse:
        """
        Lists the organizations the authenticated caller is an active member of (paginated), each with the role the caller holds in it. Returns an empty list when the caller belongs to no organizations.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationsListResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.organizations.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        type: typing.Optional[OrganizationType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Organization:
        """
        Onboards the authenticated user's partner Organization: creates the local Organization + the creator's admin membership atomically, then mirrors it to WorkOS (creates the WorkOS org and binds the creator as admin). A user may hold several organizations and selects which one a request acts as with the `X-Vitable-Organization` header. The founder's email domain is claimed only when no other organization holds it, so a taken domain is left with its owner rather than rejected.

        Parameters
        ----------
        name : str
            Legal or trading name of the organization.

        type : typing.Optional[OrganizationType]
            Category of organization being onboarded.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.organizations.create(
            name="Acme Brokerage",
            type="BROKERAGE",
        )
        """
        _response = self._raw_client.create(name=name, type=type, request_options=request_options)
        return _response.data


class AsyncOrganizationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrganizationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrganizationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrganizationsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationsListResponse:
        """
        Lists the organizations the authenticated caller is an active member of (paginated), each with the role the caller holds in it. Returns an empty list when the caller belongs to no organizations.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationsListResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        type: typing.Optional[OrganizationType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Organization:
        """
        Onboards the authenticated user's partner Organization: creates the local Organization + the creator's admin membership atomically, then mirrors it to WorkOS (creates the WorkOS org and binds the creator as admin). A user may hold several organizations and selects which one a request acts as with the `X-Vitable-Organization` header. The founder's email domain is claimed only when no other organization holds it, so a taken domain is left with its owner rather than rejected.

        Parameters
        ----------
        name : str
            Legal or trading name of the organization.

        type : typing.Optional[OrganizationType]
            Category of organization being onboarded.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.create(
                name="Acme Brokerage",
                type="BROKERAGE",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(name=name, type=type, request_options=request_options)
        return _response.data
