# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.group_id import GroupId
from ....types.group_member_sync_detail_response import GroupMemberSyncDetailResponse
from ....types.group_member_sync_member_request import GroupMemberSyncMemberRequest
from ....types.group_member_sync_request_detail_response import GroupMemberSyncRequestDetailResponse
from ....types.request_id import RequestId
from .raw_client import AsyncRawSyncClient, RawSyncClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SyncClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSyncClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSyncClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSyncClient
        """
        return self._raw_client

    def submit(
        self,
        group_id: GroupId,
        *,
        members: typing.Sequence[GroupMemberSyncMemberRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GroupMemberSyncDetailResponse:
        """
        Submits a member sync payload for the specified group. Members in the payload will be queued for processing asynchronously. Returns HTTP 202 with the batch ID and acceptance timestamp.

        Parameters
        ----------
        group_id : GroupId

        members : typing.Sequence[GroupMemberSyncMemberRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GroupMemberSyncDetailResponse


        Examples
        --------
        import datetime

        from vitable_connect import (
            AddressRequest,
            GroupMemberSyncMemberRequest,
            VitableConnect,
        )

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.groups.members.sync.submit(
            group_id="grp_abc123def456",
            members=[
                GroupMemberSyncMemberRequest(
                    reference_id="EMP-001",
                    first_name="Jane",
                    last_name="Doe",
                    date_of_birth=datetime.date.fromisoformat(
                        "1990-05-15",
                    ),
                    phone="4155550100",
                    plan_id="pln_abc123def456",
                    address=AddressRequest(
                        address_line1="123 Main Street",
                        address_line2="Apt 4B",
                        city="San Francisco",
                        state="CA",
                        zipcode="94102",
                    ),
                    email="jane.doe@acme.com",
                )
            ],
        )
        """
        _response = self._raw_client.submit(group_id, members=members, request_options=request_options)
        return _response.data

    def get(
        self, group_id: GroupId, request_id: RequestId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GroupMemberSyncRequestDetailResponse:
        """
        Retrieves a previously-submitted group member sync request by its `grpmsr_` ID. Returns the acceptance timestamp, completion timestamp (if processing has finished), and the per-member `results` once available. While processing is in flight, `completed_at` and `results` are `null`.

        Parameters
        ----------
        group_id : GroupId

        request_id : RequestId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GroupMemberSyncRequestDetailResponse


        Examples
        --------
        from vitable_connect import VitableConnect

        client = VitableConnect(
            api_key="YOUR_API_KEY",
        )
        client.groups.members.sync.get(
            group_id="grp_abc123def456",
            request_id="request_id",
        )
        """
        _response = self._raw_client.get(group_id, request_id, request_options=request_options)
        return _response.data


class AsyncSyncClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSyncClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSyncClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSyncClient
        """
        return self._raw_client

    async def submit(
        self,
        group_id: GroupId,
        *,
        members: typing.Sequence[GroupMemberSyncMemberRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GroupMemberSyncDetailResponse:
        """
        Submits a member sync payload for the specified group. Members in the payload will be queued for processing asynchronously. Returns HTTP 202 with the batch ID and acceptance timestamp.

        Parameters
        ----------
        group_id : GroupId

        members : typing.Sequence[GroupMemberSyncMemberRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GroupMemberSyncDetailResponse


        Examples
        --------
        import asyncio
        import datetime

        from vitable_connect import (
            AddressRequest,
            AsyncVitableConnect,
            GroupMemberSyncMemberRequest,
        )

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.groups.members.sync.submit(
                group_id="grp_abc123def456",
                members=[
                    GroupMemberSyncMemberRequest(
                        reference_id="EMP-001",
                        first_name="Jane",
                        last_name="Doe",
                        date_of_birth=datetime.date.fromisoformat(
                            "1990-05-15",
                        ),
                        phone="4155550100",
                        plan_id="pln_abc123def456",
                        address=AddressRequest(
                            address_line1="123 Main Street",
                            address_line2="Apt 4B",
                            city="San Francisco",
                            state="CA",
                            zipcode="94102",
                        ),
                        email="jane.doe@acme.com",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.submit(group_id, members=members, request_options=request_options)
        return _response.data

    async def get(
        self, group_id: GroupId, request_id: RequestId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GroupMemberSyncRequestDetailResponse:
        """
        Retrieves a previously-submitted group member sync request by its `grpmsr_` ID. Returns the acceptance timestamp, completion timestamp (if processing has finished), and the per-member `results` once available. While processing is in flight, `completed_at` and `results` are `null`.

        Parameters
        ----------
        group_id : GroupId

        request_id : RequestId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GroupMemberSyncRequestDetailResponse


        Examples
        --------
        import asyncio

        from vitable_connect import AsyncVitableConnect

        client = AsyncVitableConnect(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.groups.members.sync.get(
                group_id="grp_abc123def456",
                request_id="request_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(group_id, request_id, request_options=request_options)
        return _response.data
