# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .access_method import AccessMethod
    from .access_token_response import AccessTokenResponse
    from .additional_access_method import AdditionalAccessMethod
    from .address import Address
    from .address_request import AddressRequest
    from .benefit_family import BenefitFamily
    from .benefit_family_param_item import BenefitFamilyParamItem
    from .benefit_lifecycle_stage_item import BenefitLifecycleStageItem
    from .benefit_plan_network import BenefitPlanNetwork
    from .benefit_plan_year_detail import BenefitPlanYearDetail
    from .benefit_plan_year_id import BenefitPlanYearId
    from .benefit_plan_year_list import BenefitPlanYearList
    from .benefit_status import BenefitStatus
    from .benefit_summary import BenefitSummary
    from .bound_entity import BoundEntity
    from .bound_entity_response import BoundEntityResponse
    from .bound_entity_type import BoundEntityType
    from .card_type import CardType
    from .category import Category
    from .census_sync_detail_response import CensusSyncDetailResponse
    from .census_sync_employee_address_request import CensusSyncEmployeeAddressRequest
    from .census_sync_employee_request import CensusSyncEmployeeRequest
    from .census_sync_response import CensusSyncResponse
    from .classification_correction_source import ClassificationCorrectionSource
    from .compensation_type import CompensationType
    from .contribution_class_compensation import ContributionClassCompensation
    from .contribution_class_employment import ContributionClassEmployment
    from .contribution_class_location import ContributionClassLocation
    from .contribution_range import ContributionRange
    from .contribution_strategy import ContributionStrategy
    from .contribution_tier import ContributionTier
    from .coverage_tier import CoverageTier
    from .create_organization_request_type import CreateOrganizationRequestType
    from .created_after import CreatedAfter
    from .created_before import CreatedBefore
    from .deduction_detail import DeductionDetail
    from .deduction_frequency import DeductionFrequency
    from .digital_benefit_card import DigitalBenefitCard
    from .election_status_item import ElectionStatusItem
    from .eligibility_policy import EligibilityPolicy
    from .eligibility_policy_rule import EligibilityPolicyRule
    from .eligibility_rule_compensation_type import EligibilityRuleCompensationType
    from .eligibility_rule_employee_class import EligibilityRuleEmployeeClass
    from .eligible_geographical_location import EligibleGeographicalLocation
    from .eligible_geographical_location_type import EligibleGeographicalLocationType
    from .employee import Employee
    from .employee_address import EmployeeAddress
    from .employee_address_input import EmployeeAddressInput
    from .employee_class import EmployeeClass
    from .employee_id import EmployeeId
    from .employee_list_response import EmployeeListResponse
    from .employee_response import EmployeeResponse
    from .employee_search import EmployeeSearch
    from .employee_status import EmployeeStatus
    from .employer import Employer
    from .employer_address import EmployerAddress
    from .employer_address_input import EmployerAddressInput
    from .employer_benefit_lifecycle_stage import EmployerBenefitLifecycleStage
    from .employer_benefit_plan_year_response import EmployerBenefitPlanYearResponse
    from .employer_benefit_plan_years_list_response import EmployerBenefitPlanYearsListResponse
    from .employer_contact import EmployerContact
    from .employer_hris import EmployerHris
    from .employer_hris_response import EmployerHrisResponse
    from .employer_hris_status import EmployerHrisStatus
    from .employer_id import EmployerId
    from .employer_invoice_pdf import EmployerInvoicePdf
    from .employer_invoice_pdf_response import EmployerInvoicePdfResponse
    from .employer_invoices_list_response import EmployerInvoicesListResponse
    from .employer_payroll_deduction_statement_list_response import EmployerPayrollDeductionStatementListResponse
    from .employer_response import EmployerResponse
    from .employer_search import EmployerSearch
    from .employer_settings import EmployerSettings
    from .employer_settings_response import EmployerSettingsResponse
    from .enrollment import Enrollment
    from .enrollment_detail import EnrollmentDetail
    from .enrollment_id import EnrollmentId
    from .enrollment_list_response import EnrollmentListResponse
    from .enrollment_rate import EnrollmentRate
    from .enrollment_rate_summary import EnrollmentRateSummary
    from .enrollment_response import EnrollmentResponse
    from .enrollment_status import EnrollmentStatus
    from .error_response import ErrorResponse
    from .event_id import EventId
    from .event_name import EventName
    from .gender import Gender
    from .grant_type import GrantType
    from .group import Group
    from .group_id import GroupId
    from .group_list_response import GroupListResponse
    from .group_member_sync_detail_response import GroupMemberSyncDetailResponse
    from .group_member_sync_failure import GroupMemberSyncFailure
    from .group_member_sync_member_request import GroupMemberSyncMemberRequest
    from .group_member_sync_request_detail import GroupMemberSyncRequestDetail
    from .group_member_sync_request_detail_response import GroupMemberSyncRequestDetailResponse
    from .group_member_sync_response import GroupMemberSyncResponse
    from .group_member_sync_results import GroupMemberSyncResults
    from .group_response import GroupResponse
    from .household_member import HouseholdMember
    from .household_member_relationship import HouseholdMemberRelationship
    from .household_member_type import HouseholdMemberType
    from .household_members_response import HouseholdMembersResponse
    from .hris_connection import HrisConnection
    from .hris_status_item import HrisStatusItem
    from .ichra_contribution_class import IchraContributionClass
    from .idp_provider import IdpProvider
    from .include_cancelled import IncludeCancelled
    from .invoice import Invoice
    from .invoice_id import InvoiceId
    from .invoices_cursor_pagination import InvoicesCursorPagination
    from .limit import Limit
    from .list_webhook_event_deliveries_response import ListWebhookEventDeliveriesResponse
    from .marital_status import MaritalStatus
    from .member import Member
    from .member_address import MemberAddress
    from .member_dependents_response import MemberDependentsResponse
    from .member_digital_benefit_cards_response import MemberDigitalBenefitCardsResponse
    from .member_employments_response import MemberEmploymentsResponse
    from .member_enrollment import MemberEnrollment
    from .member_enrollments_response import MemberEnrollmentsResponse
    from .member_id import MemberId
    from .member_legal_dependent import MemberLegalDependent
    from .member_list_item import MemberListItem
    from .member_list_response import MemberListResponse
    from .member_qualifying_life_event import MemberQualifyingLifeEvent
    from .member_qualifying_life_event_list_response import MemberQualifyingLifeEventListResponse
    from .member_response import MemberResponse
    from .member_search import MemberSearch
    from .member_status import MemberStatus
    from .missing_employee_resolution import MissingEmployeeResolution
    from .name_suffix import NameSuffix
    from .offset import Offset
    from .operation import Operation
    from .organization import Organization
    from .organization_employer import OrganizationEmployer
    from .organization_employer_list_response import OrganizationEmployerListResponse
    from .organization_hris_provider import OrganizationHrisProvider
    from .organization_hris_providers_response import OrganizationHrisProvidersResponse
    from .organization_type import OrganizationType
    from .organizations_list_response import OrganizationsListResponse
    from .page import Page
    from .pagination import Pagination
    from .payroll_access_setup_status import PayrollAccessSetupStatus
    from .payroll_access_setup_status_response import PayrollAccessSetupStatusResponse
    from .payroll_deduction_statement import PayrollDeductionStatement
    from .payroll_integration_email import PayrollIntegrationEmail
    from .payroll_integration_email_response import PayrollIntegrationEmailResponse
    from .plan import Plan
    from .plan_list_response import PlanListResponse
    from .plan_year_enrollment import PlanYearEnrollment
    from .plan_year_enrollment_election_status import PlanYearEnrollmentElectionStatus
    from .plan_year_enrollment_list_response import PlanYearEnrollmentListResponse
    from .plan_year_enrollment_policy_status import PlanYearEnrollmentPolicyStatus
    from .preferred_language import PreferredLanguage
    from .product_code import ProductCode
    from .qualifying_life_event_status import QualifyingLifeEventStatus
    from .qualifying_life_event_type import QualifyingLifeEventType
    from .reissue_enrollment import ReissueEnrollment
    from .reissue_enrollment_response import ReissueEnrollmentResponse
    from .relationship import Relationship
    from .remaining_employee_action import RemainingEmployeeAction
    from .request_id import RequestId
    from .resource_id import ResourceId
    from .resource_type import ResourceType
    from .search import Search
    from .sex_at_birth import SexAtBirth
    from .state import State
    from .status import Status
    from .tax_classification import TaxClassification
    from .termination_rule import TerminationRule
    from .update_employer_address_input import UpdateEmployerAddressInput
    from .waiting_period import WaitingPeriod
    from .webhook_delivery import WebhookDelivery
    from .webhook_event import WebhookEvent
    from .webhook_event_list_response import WebhookEventListResponse
    from .webhook_event_response import WebhookEventResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AccessMethod": ".access_method",
    "AccessTokenResponse": ".access_token_response",
    "AdditionalAccessMethod": ".additional_access_method",
    "Address": ".address",
    "AddressRequest": ".address_request",
    "BenefitFamily": ".benefit_family",
    "BenefitFamilyParamItem": ".benefit_family_param_item",
    "BenefitLifecycleStageItem": ".benefit_lifecycle_stage_item",
    "BenefitPlanNetwork": ".benefit_plan_network",
    "BenefitPlanYearDetail": ".benefit_plan_year_detail",
    "BenefitPlanYearId": ".benefit_plan_year_id",
    "BenefitPlanYearList": ".benefit_plan_year_list",
    "BenefitStatus": ".benefit_status",
    "BenefitSummary": ".benefit_summary",
    "BoundEntity": ".bound_entity",
    "BoundEntityResponse": ".bound_entity_response",
    "BoundEntityType": ".bound_entity_type",
    "CardType": ".card_type",
    "Category": ".category",
    "CensusSyncDetailResponse": ".census_sync_detail_response",
    "CensusSyncEmployeeAddressRequest": ".census_sync_employee_address_request",
    "CensusSyncEmployeeRequest": ".census_sync_employee_request",
    "CensusSyncResponse": ".census_sync_response",
    "ClassificationCorrectionSource": ".classification_correction_source",
    "CompensationType": ".compensation_type",
    "ContributionClassCompensation": ".contribution_class_compensation",
    "ContributionClassEmployment": ".contribution_class_employment",
    "ContributionClassLocation": ".contribution_class_location",
    "ContributionRange": ".contribution_range",
    "ContributionStrategy": ".contribution_strategy",
    "ContributionTier": ".contribution_tier",
    "CoverageTier": ".coverage_tier",
    "CreateOrganizationRequestType": ".create_organization_request_type",
    "CreatedAfter": ".created_after",
    "CreatedBefore": ".created_before",
    "DeductionDetail": ".deduction_detail",
    "DeductionFrequency": ".deduction_frequency",
    "DigitalBenefitCard": ".digital_benefit_card",
    "ElectionStatusItem": ".election_status_item",
    "EligibilityPolicy": ".eligibility_policy",
    "EligibilityPolicyRule": ".eligibility_policy_rule",
    "EligibilityRuleCompensationType": ".eligibility_rule_compensation_type",
    "EligibilityRuleEmployeeClass": ".eligibility_rule_employee_class",
    "EligibleGeographicalLocation": ".eligible_geographical_location",
    "EligibleGeographicalLocationType": ".eligible_geographical_location_type",
    "Employee": ".employee",
    "EmployeeAddress": ".employee_address",
    "EmployeeAddressInput": ".employee_address_input",
    "EmployeeClass": ".employee_class",
    "EmployeeId": ".employee_id",
    "EmployeeListResponse": ".employee_list_response",
    "EmployeeResponse": ".employee_response",
    "EmployeeSearch": ".employee_search",
    "EmployeeStatus": ".employee_status",
    "Employer": ".employer",
    "EmployerAddress": ".employer_address",
    "EmployerAddressInput": ".employer_address_input",
    "EmployerBenefitLifecycleStage": ".employer_benefit_lifecycle_stage",
    "EmployerBenefitPlanYearResponse": ".employer_benefit_plan_year_response",
    "EmployerBenefitPlanYearsListResponse": ".employer_benefit_plan_years_list_response",
    "EmployerContact": ".employer_contact",
    "EmployerHris": ".employer_hris",
    "EmployerHrisResponse": ".employer_hris_response",
    "EmployerHrisStatus": ".employer_hris_status",
    "EmployerId": ".employer_id",
    "EmployerInvoicePdf": ".employer_invoice_pdf",
    "EmployerInvoicePdfResponse": ".employer_invoice_pdf_response",
    "EmployerInvoicesListResponse": ".employer_invoices_list_response",
    "EmployerPayrollDeductionStatementListResponse": ".employer_payroll_deduction_statement_list_response",
    "EmployerResponse": ".employer_response",
    "EmployerSearch": ".employer_search",
    "EmployerSettings": ".employer_settings",
    "EmployerSettingsResponse": ".employer_settings_response",
    "Enrollment": ".enrollment",
    "EnrollmentDetail": ".enrollment_detail",
    "EnrollmentId": ".enrollment_id",
    "EnrollmentListResponse": ".enrollment_list_response",
    "EnrollmentRate": ".enrollment_rate",
    "EnrollmentRateSummary": ".enrollment_rate_summary",
    "EnrollmentResponse": ".enrollment_response",
    "EnrollmentStatus": ".enrollment_status",
    "ErrorResponse": ".error_response",
    "EventId": ".event_id",
    "EventName": ".event_name",
    "Gender": ".gender",
    "GrantType": ".grant_type",
    "Group": ".group",
    "GroupId": ".group_id",
    "GroupListResponse": ".group_list_response",
    "GroupMemberSyncDetailResponse": ".group_member_sync_detail_response",
    "GroupMemberSyncFailure": ".group_member_sync_failure",
    "GroupMemberSyncMemberRequest": ".group_member_sync_member_request",
    "GroupMemberSyncRequestDetail": ".group_member_sync_request_detail",
    "GroupMemberSyncRequestDetailResponse": ".group_member_sync_request_detail_response",
    "GroupMemberSyncResponse": ".group_member_sync_response",
    "GroupMemberSyncResults": ".group_member_sync_results",
    "GroupResponse": ".group_response",
    "HouseholdMember": ".household_member",
    "HouseholdMemberRelationship": ".household_member_relationship",
    "HouseholdMemberType": ".household_member_type",
    "HouseholdMembersResponse": ".household_members_response",
    "HrisConnection": ".hris_connection",
    "HrisStatusItem": ".hris_status_item",
    "IchraContributionClass": ".ichra_contribution_class",
    "IdpProvider": ".idp_provider",
    "IncludeCancelled": ".include_cancelled",
    "Invoice": ".invoice",
    "InvoiceId": ".invoice_id",
    "InvoicesCursorPagination": ".invoices_cursor_pagination",
    "Limit": ".limit",
    "ListWebhookEventDeliveriesResponse": ".list_webhook_event_deliveries_response",
    "MaritalStatus": ".marital_status",
    "Member": ".member",
    "MemberAddress": ".member_address",
    "MemberDependentsResponse": ".member_dependents_response",
    "MemberDigitalBenefitCardsResponse": ".member_digital_benefit_cards_response",
    "MemberEmploymentsResponse": ".member_employments_response",
    "MemberEnrollment": ".member_enrollment",
    "MemberEnrollmentsResponse": ".member_enrollments_response",
    "MemberId": ".member_id",
    "MemberLegalDependent": ".member_legal_dependent",
    "MemberListItem": ".member_list_item",
    "MemberListResponse": ".member_list_response",
    "MemberQualifyingLifeEvent": ".member_qualifying_life_event",
    "MemberQualifyingLifeEventListResponse": ".member_qualifying_life_event_list_response",
    "MemberResponse": ".member_response",
    "MemberSearch": ".member_search",
    "MemberStatus": ".member_status",
    "MissingEmployeeResolution": ".missing_employee_resolution",
    "NameSuffix": ".name_suffix",
    "Offset": ".offset",
    "Operation": ".operation",
    "Organization": ".organization",
    "OrganizationEmployer": ".organization_employer",
    "OrganizationEmployerListResponse": ".organization_employer_list_response",
    "OrganizationHrisProvider": ".organization_hris_provider",
    "OrganizationHrisProvidersResponse": ".organization_hris_providers_response",
    "OrganizationType": ".organization_type",
    "OrganizationsListResponse": ".organizations_list_response",
    "Page": ".page",
    "Pagination": ".pagination",
    "PayrollAccessSetupStatus": ".payroll_access_setup_status",
    "PayrollAccessSetupStatusResponse": ".payroll_access_setup_status_response",
    "PayrollDeductionStatement": ".payroll_deduction_statement",
    "PayrollIntegrationEmail": ".payroll_integration_email",
    "PayrollIntegrationEmailResponse": ".payroll_integration_email_response",
    "Plan": ".plan",
    "PlanListResponse": ".plan_list_response",
    "PlanYearEnrollment": ".plan_year_enrollment",
    "PlanYearEnrollmentElectionStatus": ".plan_year_enrollment_election_status",
    "PlanYearEnrollmentListResponse": ".plan_year_enrollment_list_response",
    "PlanYearEnrollmentPolicyStatus": ".plan_year_enrollment_policy_status",
    "PreferredLanguage": ".preferred_language",
    "ProductCode": ".product_code",
    "QualifyingLifeEventStatus": ".qualifying_life_event_status",
    "QualifyingLifeEventType": ".qualifying_life_event_type",
    "ReissueEnrollment": ".reissue_enrollment",
    "ReissueEnrollmentResponse": ".reissue_enrollment_response",
    "Relationship": ".relationship",
    "RemainingEmployeeAction": ".remaining_employee_action",
    "RequestId": ".request_id",
    "ResourceId": ".resource_id",
    "ResourceType": ".resource_type",
    "Search": ".search",
    "SexAtBirth": ".sex_at_birth",
    "State": ".state",
    "Status": ".status",
    "TaxClassification": ".tax_classification",
    "TerminationRule": ".termination_rule",
    "UpdateEmployerAddressInput": ".update_employer_address_input",
    "WaitingPeriod": ".waiting_period",
    "WebhookDelivery": ".webhook_delivery",
    "WebhookEvent": ".webhook_event",
    "WebhookEventListResponse": ".webhook_event_list_response",
    "WebhookEventResponse": ".webhook_event_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AccessMethod",
    "AccessTokenResponse",
    "AdditionalAccessMethod",
    "Address",
    "AddressRequest",
    "BenefitFamily",
    "BenefitFamilyParamItem",
    "BenefitLifecycleStageItem",
    "BenefitPlanNetwork",
    "BenefitPlanYearDetail",
    "BenefitPlanYearId",
    "BenefitPlanYearList",
    "BenefitStatus",
    "BenefitSummary",
    "BoundEntity",
    "BoundEntityResponse",
    "BoundEntityType",
    "CardType",
    "Category",
    "CensusSyncDetailResponse",
    "CensusSyncEmployeeAddressRequest",
    "CensusSyncEmployeeRequest",
    "CensusSyncResponse",
    "ClassificationCorrectionSource",
    "CompensationType",
    "ContributionClassCompensation",
    "ContributionClassEmployment",
    "ContributionClassLocation",
    "ContributionRange",
    "ContributionStrategy",
    "ContributionTier",
    "CoverageTier",
    "CreateOrganizationRequestType",
    "CreatedAfter",
    "CreatedBefore",
    "DeductionDetail",
    "DeductionFrequency",
    "DigitalBenefitCard",
    "ElectionStatusItem",
    "EligibilityPolicy",
    "EligibilityPolicyRule",
    "EligibilityRuleCompensationType",
    "EligibilityRuleEmployeeClass",
    "EligibleGeographicalLocation",
    "EligibleGeographicalLocationType",
    "Employee",
    "EmployeeAddress",
    "EmployeeAddressInput",
    "EmployeeClass",
    "EmployeeId",
    "EmployeeListResponse",
    "EmployeeResponse",
    "EmployeeSearch",
    "EmployeeStatus",
    "Employer",
    "EmployerAddress",
    "EmployerAddressInput",
    "EmployerBenefitLifecycleStage",
    "EmployerBenefitPlanYearResponse",
    "EmployerBenefitPlanYearsListResponse",
    "EmployerContact",
    "EmployerHris",
    "EmployerHrisResponse",
    "EmployerHrisStatus",
    "EmployerId",
    "EmployerInvoicePdf",
    "EmployerInvoicePdfResponse",
    "EmployerInvoicesListResponse",
    "EmployerPayrollDeductionStatementListResponse",
    "EmployerResponse",
    "EmployerSearch",
    "EmployerSettings",
    "EmployerSettingsResponse",
    "Enrollment",
    "EnrollmentDetail",
    "EnrollmentId",
    "EnrollmentListResponse",
    "EnrollmentRate",
    "EnrollmentRateSummary",
    "EnrollmentResponse",
    "EnrollmentStatus",
    "ErrorResponse",
    "EventId",
    "EventName",
    "Gender",
    "GrantType",
    "Group",
    "GroupId",
    "GroupListResponse",
    "GroupMemberSyncDetailResponse",
    "GroupMemberSyncFailure",
    "GroupMemberSyncMemberRequest",
    "GroupMemberSyncRequestDetail",
    "GroupMemberSyncRequestDetailResponse",
    "GroupMemberSyncResponse",
    "GroupMemberSyncResults",
    "GroupResponse",
    "HouseholdMember",
    "HouseholdMemberRelationship",
    "HouseholdMemberType",
    "HouseholdMembersResponse",
    "HrisConnection",
    "HrisStatusItem",
    "IchraContributionClass",
    "IdpProvider",
    "IncludeCancelled",
    "Invoice",
    "InvoiceId",
    "InvoicesCursorPagination",
    "Limit",
    "ListWebhookEventDeliveriesResponse",
    "MaritalStatus",
    "Member",
    "MemberAddress",
    "MemberDependentsResponse",
    "MemberDigitalBenefitCardsResponse",
    "MemberEmploymentsResponse",
    "MemberEnrollment",
    "MemberEnrollmentsResponse",
    "MemberId",
    "MemberLegalDependent",
    "MemberListItem",
    "MemberListResponse",
    "MemberQualifyingLifeEvent",
    "MemberQualifyingLifeEventListResponse",
    "MemberResponse",
    "MemberSearch",
    "MemberStatus",
    "MissingEmployeeResolution",
    "NameSuffix",
    "Offset",
    "Operation",
    "Organization",
    "OrganizationEmployer",
    "OrganizationEmployerListResponse",
    "OrganizationHrisProvider",
    "OrganizationHrisProvidersResponse",
    "OrganizationType",
    "OrganizationsListResponse",
    "Page",
    "Pagination",
    "PayrollAccessSetupStatus",
    "PayrollAccessSetupStatusResponse",
    "PayrollDeductionStatement",
    "PayrollIntegrationEmail",
    "PayrollIntegrationEmailResponse",
    "Plan",
    "PlanListResponse",
    "PlanYearEnrollment",
    "PlanYearEnrollmentElectionStatus",
    "PlanYearEnrollmentListResponse",
    "PlanYearEnrollmentPolicyStatus",
    "PreferredLanguage",
    "ProductCode",
    "QualifyingLifeEventStatus",
    "QualifyingLifeEventType",
    "ReissueEnrollment",
    "ReissueEnrollmentResponse",
    "Relationship",
    "RemainingEmployeeAction",
    "RequestId",
    "ResourceId",
    "ResourceType",
    "Search",
    "SexAtBirth",
    "State",
    "Status",
    "TaxClassification",
    "TerminationRule",
    "UpdateEmployerAddressInput",
    "WaitingPeriod",
    "WebhookDelivery",
    "WebhookEvent",
    "WebhookEventListResponse",
    "WebhookEventResponse",
]
