# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bound_entity_response import BoundEntityResponse


class AccessTokenResponse(UniversalBaseModel):
    access_token: str = pydantic.Field()
    """
    The issued access token (vit_at_*)
    """

    token_type: str = pydantic.Field()
    """
    Token type, always 'Bearer'
    """

    expires_in: int = pydantic.Field()
    """
    Token lifetime in seconds
    """

    bound_entity: typing.Optional[BoundEntityResponse] = pydantic.Field(default=None)
    """
    Entity the token is bound to, if any
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
