# This file was auto-generated by Fern from our API Definition.

import typing

BenefitLifecycleStageItem = typing.Union[
    typing.Literal["open_enrollment", "renewal", "active", "onboarding", "cancelled"], typing.Any
]
