# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .benefit_family import BenefitFamily
from .benefit_status import BenefitStatus
from .contribution_range import ContributionRange
from .contribution_strategy import ContributionStrategy
from .eligibility_policy import EligibilityPolicy
from .enrollment_rate import EnrollmentRate


class BenefitPlanYearDetail(UniversalBaseModel):
    """
    One plan year, detail view.

    Standalone (no shared base) so the exact detail payload is readable in one place; the list
    serializer is a separate class even where fields overlap. Detail carries the SPD link and omits
    the list-only ``is_current`` flag.
    """

    benefit_plan_year_id: str = pydantic.Field()
    """
    Prefixed plan-year identifier (`plyr_*`).
    """

    benefit_id: str = pydantic.Field()
    """
    Prefixed benefit identifier (`bprd_*`).
    """

    year: int = pydantic.Field()
    """
    Calendar coverage year.
    """

    family: BenefitFamily = pydantic.Field()
    """
    Benefit family.
    
    * `mec` - Mec
    * `mvp` - Mvp
    * `ichra` - Ichra
    * `vpc` - Vpc
    * `dental` - Dental
    * `vision` - Vision
    """

    product_name: str = pydantic.Field()
    """
    Benefit/product display name.
    """

    carrier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Carrier name, or null (e.g. ICHRA).
    """

    network_names: typing.List[str] = pydantic.Field()
    """
    Displayed networks: ["multi"] for ICHRA, otherwise the plan year's distinct network names.
    """

    premium_in_cents: typing.Optional[int] = pydantic.Field(default=None)
    """
    Monthly premium in cents; only for an ICHRA benefit with effective coverage.
    """

    employee_contribution: typing.Optional[ContributionRange] = pydantic.Field(default=None)
    """
    Employee contribution range.
    """

    employer_contribution: typing.Optional[ContributionRange] = pydantic.Field(default=None)
    """
    Employer contribution range.
    """

    status: BenefitStatus = pydantic.Field()
    """
    `active`/`upcoming`/`inactive`.
    
    * `active` - Active
    * `upcoming` - Upcoming
    * `open_enrollment` - Open Enrollment
    * `inactive` - Inactive
    """

    coverage_start: dt.date = pydantic.Field()
    """
    Coverage start.
    """

    coverage_end: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Coverage end.
    """

    open_enrollment_start: dt.date = pydantic.Field()
    """
    Open-enrollment start.
    """

    open_enrollment_end: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Open-enrollment end.
    """

    offered_states: typing.List[str] = pydantic.Field()
    """
    Distinct offered state codes.
    """

    enrollment_rate: EnrollmentRate = pydantic.Field()
    """
    Enrolled/eligible rate for this plan year.
    """

    spd_file_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Summary Plan Description (SPD) link, or null.
    """

    contribution_strategy: ContributionStrategy = pydantic.Field()
    """
    How the plan year prices contributions (ICHRA classes or coverage tiers).
    """

    eligibility_policy: typing.Optional[EligibilityPolicy] = pydantic.Field(default=None)
    """
    The plan year's active eligibility policy, or null.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
