# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bound_entity_type import BoundEntityType


class BoundEntity(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Prefixed entity ID to bind the token to (empr_* for employer, empl_* for employee)
    """

    type: BoundEntityType = pydantic.Field()
    """
    Type of entity: 'employer' or 'employee'
    
    * `employer` - employer
    * `employee` - employee
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
