# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CensusSyncResponse(UniversalBaseModel):
    employer_id: str = pydantic.Field()
    """
    Employer the census sync was submitted for (`empr_*`).
    """

    accepted_at: dt.datetime = pydantic.Field()
    """
    When Vitable accepted the census sync for processing (RFC 3339).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
