# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .census_sync_employee_address_request import CensusSyncEmployeeAddressRequest
from .compensation_type import CompensationType
from .employee_class import EmployeeClass


class CensusSyncEmployeeRequest(UniversalBaseModel):
    reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Your own identifier for this employee. Vitable echoes it back on sync results so you can match failures to your records.
    """

    first_name: str = pydantic.Field()
    """
    Employee's legal first name.
    """

    last_name: str = pydantic.Field()
    """
    Employee's legal last name.
    """

    date_of_birth: dt.date = pydantic.Field()
    """
    Employee's date of birth as `YYYY-MM-DD`. Used to match existing members.
    """

    email: str = pydantic.Field()
    """
    Employee's work email address. Vitable sends enrollment invitations here.
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone number
    """

    address: typing.Optional[CensusSyncEmployeeAddressRequest] = pydantic.Field(default=None)
    """
    Employee's home address, used to determine plan availability.
    """

    start_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Employment start date as `YYYY-MM-DD`. Drives benefit eligibility dates.
    """

    employee_class: typing.Optional[EmployeeClass] = pydantic.Field(default=None)
    """
    Employee class used to match the employer's eligibility policy rules.
    """

    compensation_type: typing.Optional[CompensationType] = pydantic.Field(default=None)
    """
    Whether the employee is salaried or hourly.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
