# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .contribution_tier import ContributionTier
from .ichra_contribution_class import IchraContributionClass


class ContributionStrategy(UniversalBaseModel):
    """
    How the plan year prices contributions: exactly one collection is populated, determined by the
    plan year's ``family`` (ICHRA vs tier-priced).
    """

    ichra_contribution_classes: typing.List[IchraContributionClass] = pydantic.Field()
    """
    ICHRA contribution classes; empty for tier-priced benefits.
    """

    contribution_tiers: typing.List[ContributionTier] = pydantic.Field()
    """
    Coverage tiers and their costs; empty for ICHRA benefits.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
