# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .state import State


class CreateMemberDependentAddressRequest(UniversalBaseModel):
    address_line1: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="address_line_1"),
        pydantic.Field(alias="address_line_1", description="Primary street address"),
    ]
    """
    Primary street address
    """

    address_line2: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="address_line_2"),
        pydantic.Field(alias="address_line_2", description="Secondary street address"),
    ] = None
    """
    Secondary street address
    """

    city: str = pydantic.Field()
    """
    City name
    """

    state: State = pydantic.Field()
    """
    Two-letter state code
    
    * `AL` - AL
    * `AK` - AK
    * `AZ` - AZ
    * `AR` - AR
    * `CA` - CA
    * `CO` - CO
    * `CT` - CT
    * `DC` - DC
    * `DE` - DE
    * `FL` - FL
    * `GA` - GA
    * `HI` - HI
    * `ID` - ID
    * `IL` - IL
    * `IN` - IN
    * `IA` - IA
    * `KS` - KS
    * `KY` - KY
    * `LA` - LA
    * `ME` - ME
    * `MD` - MD
    * `MA` - MA
    * `MI` - MI
    * `MN` - MN
    * `MS` - MS
    * `MO` - MO
    * `MT` - MT
    * `NE` - NE
    * `NV` - NV
    * `NH` - NH
    * `NJ` - NJ
    * `NM` - NM
    * `NY` - NY
    * `NC` - NC
    * `ND` - ND
    * `OH` - OH
    * `OK` - OK
    * `OR` - OR
    * `PA` - PA
    * `RI` - RI
    * `SC` - SC
    * `SD` - SD
    * `TN` - TN
    * `TX` - TX
    * `UT` - UT
    * `VT` - VT
    * `VA` - VA
    * `WA` - WA
    * `WI` - WI
    * `WV` - WV
    * `WY` - WY
    * `PR` - PR
    * `GU` - GU
    * `AS` - AS
    * `VI` - VI
    * `MP` - MP
    * `MH` - MH
    * `PW` - PW
    * `FM` - FM
    * `AE` - AE
    * `AA` - AA
    * `AP` - AP
    """

    zipcode: str = pydantic.Field()
    """
    ZIP code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
