# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deduction_frequency import DeductionFrequency
from .tax_classification import TaxClassification


class DeductionDetail(UniversalBaseModel):
    deduction_category: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deduction category (reserved for future use)
    """

    deduction_amount_in_cents: int = pydantic.Field()
    """
    Employee deduction amount in cents
    """

    tax_classification: TaxClassification = pydantic.Field()
    """
    Tax classification: Pre-tax, Post-tax, or Unknown
    
    * `Unknown` - Unknown
    * `Pre-tax` - Pre Tax
    * `Post-tax` - Post Tax
    """

    frequency: DeductionFrequency = pydantic.Field()
    """
    Deduction frequency
    
    * `weekly` - Weekly
    * `bi_weekly` - Bi Weekly
    * `semi_monthly` - Semi Monthly
    * `monthly` - Monthly
    """

    benefit_name: str = pydantic.Field()
    """
    Name of the benefit plan
    """

    period_start_date: dt.date = pydantic.Field()
    """
    Period start date (YYYY-MM-DD)
    """

    period_end_date: dt.date = pydantic.Field()
    """
    Period end date (YYYY-MM-DD)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
