# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .state import State


class DetailedAddress(UniversalBaseModel):
    address_line1: typing_extensions.Annotated[
        str, FieldMetadata(alias="address_line_1"), pydantic.Field(alias="address_line_1")
    ]
    address_line2: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="address_line_2"), pydantic.Field(alias="address_line_2")
    ] = None
    city: str
    zipcode: str
    state: State
    latitude: typing.Optional[float] = None
    longitude: typing.Optional[float] = None
    county_fips_code: typing.Optional[str] = None
    county_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
