# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .benefit_plan_network import BenefitPlanNetwork
from .card_type import CardType
from .product_code import ProductCode


class DigitalBenefitCard(UniversalBaseModel):
    """
    Wire serializer for :class:`DigitalBenefitCardDTO` (one benefit ID card).
    """

    card_type: CardType = pydantic.Field()
    """
    Kind of card: medical, dental, vision, or rx
    
    * `medical` - medical
    * `dental` - dental
    * `vision` - vision
    * `rx` - rx
    """

    group_id: str = pydantic.Field()
    """
    Group number printed on the card (the rx group id for an rx card)
    """

    group_member_id: str = pydantic.Field()
    """
    Member id printed on the card (the Ventegra cardholder id for an rx card)
    """

    member_name: str = pydantic.Field()
    """
    Name of the member the card is issued to
    """

    employer_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Employer the card's coverage is through; null for an rx card without group info
    """

    plan_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Benefit plan name on the card; null for a consumer-membership rx card
    """

    benefit_code: typing.Optional[ProductCode] = pydantic.Field(default=None)
    """
    Benefit code backing the card; null for a consumer-membership rx card, which has no enrollment
    
    * `EBA` - Eba Mec
    * `VPC` - Vpc Enhanced
    * `VPC_CORE` - Vpc Core
    * `MEC` - Vpc Mec
    * `MEC2` - Mec2
    * `MEC_PLUS` - Mec Plus
    * `MVP` - Mvp
    * `MVP2` - Mvp2
    * `MVPSL` - Mvpsl
    * `MVPSL2` - Mvpsl2
    * `VD` - Dental
    * `VV` - Vision
    * `ICHRA` - Ichra
    * `ICHRA_PREMIUM_PLUS` - Ichra Premium Plus
    * `ICHRA_REIMBURSEMENT_ONLY` - Ichra Reimbursement Only
    """

    network: typing.Optional[BenefitPlanNetwork] = pydantic.Field(default=None)
    """
    Provider network shown on the card; null for an rx card
    """

    claims_payer_display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Claims payer shown on the card
    """

    carrier_phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Carrier phone number on the card; null for an rx card
    """

    carrier_website: typing.Optional[str] = pydantic.Field(default=None)
    """
    Carrier website on the card; null for an rx card
    """

    plan_disclaimer: typing.Optional[str] = pydantic.Field(default=None)
    """
    Plan-specific disclaimer text; null for an rx card
    """

    general_disclaimer: typing.Optional[str] = pydantic.Field(default=None)
    """
    General disclaimer text; null for an rx card
    """

    nsa_table: typing.List[typing.List[str]] = pydantic.Field()
    """
    No Surprises Act cost-sharing table rendered on the card; empty for an rx card
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
