# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .eligibility_rule_compensation_type import EligibilityRuleCompensationType
from .eligibility_rule_employee_class import EligibilityRuleEmployeeClass
from .eligible_geographical_location import EligibleGeographicalLocation


class EligibilityPolicyRule(UniversalBaseModel):
    """
    One eligibility rule — the workforce slice it makes eligible. Mirrors the internal
    ``PlanYearEligibilityPolicyRuleDTO`` minus the raw ids and timestamps.
    """

    employee_class: EligibilityRuleEmployeeClass = pydantic.Field()
    """
    Employee-class matcher (`All` for any).
    
    * `Full Time` - Full Time
    * `Part Time` - Part Time
    * `Temporary` - Temporary
    * `Intern` - Intern
    * `Seasonal` - Seasonal
    * `Individual Contractor` - Individual Contractor
    * `All` - All
    """

    compensation_type: EligibilityRuleCompensationType = pydantic.Field()
    """
    Compensation matcher (`All` for any).
    
    * `Salary` - Salary
    * `Hourly` - Hourly
    * `All` - All
    """

    eligible_geographical_location: EligibleGeographicalLocation = pydantic.Field()
    """
    Geographic matcher.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
