# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .eligibility_policy_rule import EligibilityPolicyRule
from .termination_rule import TerminationRule
from .waiting_period import WaitingPeriod


class EligibilityPolicy(UniversalBaseModel):
    """
    The plan year's active eligibility policy. Mirrors the internal ``PlanYearEligibilityPolicyDTO``
    but exposes only the public subset (no raw ids, ``active_in``, or timestamps).
    """

    waiting_period: typing.Optional[WaitingPeriod] = pydantic.Field(default=None)
    """
    When coverage starts for a newly-eligible member, or null.
    
    * `FIRST_OF_FOLLOWING_MONTH` - First Of Following Month
    * `THIRTY_DAYS` - Thirty Days
    * `SIXTY_DAYS` - Sixty Days
    """

    termination_rule: TerminationRule = pydantic.Field()
    """
    When coverage ends after a member becomes ineligible.
    
    * `END_OF_N_MONTHS` - End Of N Months
    * `END_OF_PLAN_YEAR` - End Of Plan Year
    """

    termination_n_months: typing.Optional[int] = pydantic.Field(default=None)
    """
    Months of continued coverage; set only when `termination_rule` is `END_OF_N_MONTHS`.
    """

    rules: typing.List[EligibilityPolicyRule] = pydantic.Field()
    """
    Eligibility rules; never empty for a valid policy.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
