# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deduction_frequency import DeductionFrequency


class EmployerSettings(UniversalBaseModel):
    pay_frequency: typing.Optional[DeductionFrequency] = pydantic.Field(default=None)
    """
    Payroll deduction frequency. One of: weekly, bi_weekly, semi_monthly, monthly
    
    * `weekly` - Weekly
    * `bi_weekly` - Bi-Weekly
    * `semi_monthly` - Semi-Monthly
    * `monthly` - Monthly
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
