# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .employer_hris import EmployerHris


class EmployerHrisResponse(UniversalBaseModel):
    """
    Response containing a single employer hris resource.
    """

    data: EmployerHris = pydantic.Field()
    """
    The employer's HRIS connection, or `null` when no integration exists.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
