# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EmployerContact(UniversalBaseModel):
    """
    Primary company-admin contact (email + phone; company admins have no person name).
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Primary contact email
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Primary contact phone, or null
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
