# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .benefit_summary import BenefitSummary
from .enrollment_status import EnrollmentStatus


class Enrollment(UniversalBaseModel):
    """
    One enrollment as it appears in a list row.
    """

    id: str = pydantic.Field()
    """
    Unique enrollment identifier (enrl_*)
    """

    employee_id: str = pydantic.Field()
    """
    Employee ID (empl_*)
    """

    employer_id: str = pydantic.Field()
    """
    Employer ID (empr_*)
    """

    benefit: BenefitSummary = pydantic.Field()
    """
    Nested benefit product summary
    """

    status: EnrollmentStatus = pydantic.Field()
    """
    Enrollment status
    
    * `pending` - Pending
    * `enrolled` - Enrolled
    * `waived` - Waived
    * `inactive` - Inactive
    """

    coverage_start: dt.date = pydantic.Field()
    """
    Coverage period start date
    """

    coverage_end: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Coverage period end date
    """

    employee_deduction_in_cents: typing.Optional[int] = pydantic.Field(default=None)
    """
    Employee monthly payroll deduction in cents
    """

    employer_contribution_in_cents: typing.Optional[int] = pydantic.Field(default=None)
    """
    Employer monthly contribution in cents
    """

    answered_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the employee enrolled or waived
    """

    terminated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When coverage was terminated
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the enrollment was created
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the enrollment was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
