# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EnrollmentRateSummary(UniversalBaseModel):
    eligible: int = pydantic.Field()
    """
    Employees eligible for at least one active benefit.
    """

    enrolled: int = pydantic.Field()
    """
    Employees enrolled in at least one active benefit.
    """

    percentage: int = pydantic.Field()
    """
    ``enrolled / eligible`` as a whole-number percent (0 when none eligible).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
