# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .enrollment_detail import EnrollmentDetail


class EnrollmentResponse(UniversalBaseModel):
    """
    Response containing a single enrollment resource.
    """

    data: EnrollmentDetail = pydantic.Field()
    """
    The enrollment, including its elected plans.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
