# This file was auto-generated by Fern from our API Definition.

import typing

EventName = typing.Union[
    typing.Literal[
        "enrollment.accepted",
        "enrollment.terminated",
        "enrollment.termination_rescheduled",
        "enrollment.elected",
        "enrollment.granted",
        "enrollment.waived",
        "enrollment.started",
        "employee.eligibility_granted",
        "employee.eligibility_terminated",
        "employee.deactivated",
        "employee.deduction_created",
    ],
    typing.Any,
]
