# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GroupMemberSyncResponse(UniversalBaseModel):
    request_id: str = pydantic.Field()
    """
    Identifier for this sync request. Pass it to `GET /v1/groups/{group_id}/members/sync/{request_id}` to poll for results.
    """

    group_id: str = pydantic.Field()
    """
    Group whose roster is being synced (`grp_*`).
    """

    accepted_at: dt.datetime = pydantic.Field()
    """
    When Vitable accepted the sync request for processing (RFC 3339).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
