# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Group(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Prefixed group identifier (`grp_<base64-encoded-uuid>`).
    """

    organization_id: str = pydantic.Field()
    """
    Prefixed organization identifier (`org_<base64-encoded-uuid>`).
    """

    name: str = pydantic.Field()
    """
    Human-readable group name.
    """

    external_reference_id: str = pydantic.Field()
    """
    Stable identifier for this group in the integrator's own system.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Group creation timestamp (ISO 8601, UTC).
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Last-update timestamp (ISO 8601, UTC).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
