# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .group_member_sync_failure_operation import GroupMemberSyncFailureOperation


class GroupMemberSyncFailure(UniversalBaseModel):
    reference_id: str = pydantic.Field()
    """
    Your identifier for the member that failed to sync.
    """

    operation: GroupMemberSyncFailureOperation = pydantic.Field()
    """
    The sync operation that failed for this member.
    """

    reason: str = pydantic.Field()
    """
    Human-readable explanation of why the operation failed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
