# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .household_member import HouseholdMember


class HouseholdMembersResponse(UniversalBaseModel):
    """
    Unpaginated ``{"data": [...]}`` list of the members of a member's household.
    """

    data: typing.List[HouseholdMember] = pydantic.Field()
    """
    The members of the household.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
