# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Invoice(UniversalBaseModel):
    invoice_id: str = pydantic.Field()
    """
    Chargebee invoice id (external id, not a prefixed UUID).
    """

    period: typing.Optional[str] = pydantic.Field(default=None)
    """
    Invoice date as an ISO string, or null.
    """

    total: typing.Optional[float] = pydantic.Field(default=None)
    """
    Invoice total in dollars, or null.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Chargebee invoice status (e.g. `paid`), or null.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
