# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .member_legal_dependent import MemberLegalDependent


class MemberDependentsResponse(UniversalBaseModel):
    """
    Unpaginated ``{"data": [...]}`` list of member dependents.
    """

    data: typing.List[MemberLegalDependent] = pydantic.Field()
    """
    The member's legal dependents.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
