# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .member_address import MemberAddress


class MemberListItem(UniversalBaseModel):
    """
    A member in the organization's directory: identity, contact details, address, and join date.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique member identifier with 'mbr_' prefix
    """

    first_name: str = pydantic.Field()
    """
    Member's legal first name
    """

    last_name: str = pydantic.Field()
    """
    Member's legal last name
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone number (10-digit US domestic string)
    """

    address: typing.Optional[MemberAddress] = pydantic.Field(default=None)
    """
    Member's residential address
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
