# This file was auto-generated by Fern from our API Definition.

MemberSearch = str
"""
Case-insensitive search across member name, email, and phone number; exact match on member id (prefixed or raw uuid)
"""
