# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .state import State


class MemberAddress(UniversalBaseModel):
    address_line1: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="address_line_1"),
        pydantic.Field(alias="address_line_1", description="Primary street address"),
    ]
    """
    Primary street address
    """

    address_line2: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="address_line_2"),
        pydantic.Field(alias="address_line_2", description="Secondary street address (apt, suite, etc.)"),
    ] = None
    """
    Secondary street address (apt, suite, etc.)
    """

    city: str = pydantic.Field()
    """
    City name
    """

    state: State = pydantic.Field()
    """
    Two-letter state code (e.g., CA, NY)
    
    * `AL` - Al
    * `AK` - Ak
    * `AZ` - Az
    * `AR` - Ar
    * `CA` - Ca
    * `CO` - Co
    * `CT` - Ct
    * `DC` - Dc
    * `DE` - De
    * `FL` - Fl
    * `GA` - Ga
    * `HI` - Hi
    * `ID` - Id
    * `IL` - Il
    * `IN` - In
    * `IA` - Ia
    * `KS` - Ks
    * `KY` - Ky
    * `LA` - La
    * `ME` - Me
    * `MD` - Md
    * `MA` - Ma
    * `MI` - Mi
    * `MN` - Mn
    * `MS` - Ms
    * `MO` - Mo
    * `MT` - Mt
    * `NE` - Ne
    * `NV` - Nv
    * `NH` - Nh
    * `NJ` - Nj
    * `NM` - Nm
    * `NY` - Ny
    * `NC` - Nc
    * `ND` - Nd
    * `OH` - Oh
    * `OK` - Ok
    * `OR` - Or
    * `PA` - Pa
    * `RI` - Ri
    * `SC` - Sc
    * `SD` - Sd
    * `TN` - Tn
    * `TX` - Tx
    * `UT` - Ut
    * `VT` - Vt
    * `VA` - Va
    * `WA` - Wa
    * `WI` - Wi
    * `WV` - Wv
    * `WY` - Wy
    * `PR` - Pr
    * `GU` - Gu
    * `AS` - As
    * `VI` - Vi
    * `MP` - Mp
    * `MH` - Mh
    * `PW` - Pw
    * `FM` - Fm
    * `AE` - Ae
    * `AA` - Aa
    * `AP` - Ap
    """

    zipcode: str = pydantic.Field()
    """
    ZIP code (5 or 9 digit)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
