# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .relationship import Relationship
from .sex_at_birth import SexAtBirth


class MemberLegalDependent(UniversalBaseModel):
    """
    Wire serializer for :class:`MemberLegalDependentDTO` (one legal-dependent row).
    """

    member_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The dependent's own member identifier with 'mbr_' prefix
    """

    primary_member_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The primary member's identifier with 'mbr_' prefix
    """

    first_name: str = pydantic.Field()
    """
    Dependent's first name
    """

    last_name: str = pydantic.Field()
    """
    Dependent's last name
    """

    relationship: Relationship = pydantic.Field()
    """
    Relationship of the dependent to the member (e.g., Spouse, Child)
    
    * `Spouse` - Spouse
    * `Child` - Child
    """

    date_of_birth: dt.date = pydantic.Field()
    """
    Date of birth (YYYY-MM-DD)
    """

    age: int = pydantic.Field()
    """
    Dependent's age in years, derived from date of birth
    """

    sex_at_birth: typing.Optional[SexAtBirth] = pydantic.Field(default=None)
    """
    Sex assigned at birth, if provided
    
    * `Male` - Male
    * `Female` - Female
    * `Other` - Other
    * `Unknown` - Unknown
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
