# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization_employer import OrganizationEmployer
from .pagination import Pagination


class OrganizationEmployerListResponse(UniversalBaseModel):
    """
    Paginated list response containing organization employer resources.
    """

    data: typing.List[OrganizationEmployer] = pydantic.Field()
    """
    This page of employers in the organization.
    """

    pagination: Pagination = pydantic.Field()
    """
    Page metadata. Request the next page by incrementing `page`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
