# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .address import Address
from .employer_benefit_lifecycle_stage import EmployerBenefitLifecycleStage
from .employer_hris_status import EmployerHrisStatus
from .enrollment_rate_summary import EnrollmentRateSummary


class OrganizationEmployer(UniversalBaseModel):
    """
    One employer row of the organization's book (list projection).

    Carries the enriched/computed columns (enrollment roll-up, benefit-family tags, HRIS connection,
    benefit-lifecycle stage) alongside the flat CRM fields of the underlying employer (legal name,
    EIN, contact, address, timestamps) for parity with the legacy ``Employer`` contract.
    """

    employer_id: str = pydantic.Field()
    """
    Prefixed employer identifier (`empr_<base64-encoded-uuid>`).
    """

    organization_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the parent organization (`org_*`), or null when unknown.
    """

    reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The organization's own reference id for this employer, or null when none was assigned.
    """

    name: str = pydantic.Field()
    """
    Employer name.
    """

    legal_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Legal business name for compliance and tax purposes.
    """

    ein: typing.Optional[str] = pydantic.Field(default=None)
    """
    Employer Identification Number (masked in responses).
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address for billing and communications.
    """

    phone_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Employer phone number.
    """

    active: bool = pydantic.Field()
    """
    Whether the employer is currently active in the system.
    """

    address: Address = pydantic.Field()
    """
    Employer's primary address.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the employer was created.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the employer was last updated.
    """

    enrollment_rate_summary: EnrollmentRateSummary = pydantic.Field()
    """
    Enrolled/eligible employees roll-up.
    """

    benefit_families: typing.List[str] = pydantic.Field()
    """
    Distinct benefit-family tags across the employer's active benefits (e.g. `MEC`, `ICHRA`, `VPC`).
    """

    hris_status: typing.Optional[EmployerHrisStatus] = pydantic.Field(default=None)
    """
    HRIS connection, or null when the employer has none.
    """

    benefit_lifecycle_stage: EmployerBenefitLifecycleStage = pydantic.Field()
    """
    Where the employer currently sits in the benefits setup lifecycle.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
