# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .idp_provider import IdpProvider
from .organization_type import OrganizationType


class Organization(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Prefixed organization identifier (`org_<base64-encoded-uuid>`).
    """

    name: str = pydantic.Field()
    """
    Human-readable organization name.
    """

    type: typing.Optional[OrganizationType] = pydantic.Field(default=None)
    """
    Partner type (e.g. BROKERAGE, TPA).
    
    * `BROKERAGE` - Brokerage
    * `TPA` - TPA
    * `GENERAL_AGENT` - General Agent
    * `CHANNEL_PARTNER` - Channel Partner
    * `CONSULTING_FIRM` - Consulting Firm
    * `API_PLATFORM` - API Platform
    """

    idp_org_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    IdP-issued tenant id (WorkOS org id).
    """

    idp_provider: typing.Optional[IdpProvider] = pydantic.Field(default=None)
    """
    IdP that minted idp_org_id (e.g. 'workos').
    
    * `workos` - WorkOS
    * `vitable` - Vitable
    """

    super_in: bool = pydantic.Field()
    """
    Whether this organization reads across every organization.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
