# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization_hris_provider import OrganizationHrisProvider


class OrganizationHrisProvidersResponse(UniversalBaseModel):
    """
    Unpaginated ``{"data": [...]}`` list of organization hris providers.
    """

    data: typing.List[OrganizationHrisProvider] = pydantic.Field()
    """
    The HRIS providers available to the organization.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
