# This file was auto-generated by Fern from our API Definition.

import typing

OrganizationType = typing.Union[
    typing.Literal["BROKERAGE", "TPA", "GENERAL_AGENT", "CHANNEL_PARTNER", "CONSULTING_FIRM", "API_PLATFORM"],
    typing.Any,
]
