# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization import Organization


class OrganizationsListResponse(UniversalBaseModel):
    """
    Envelope for the caller's organization memberships (paginated).
    """

    organizations: typing.List[Organization] = pydantic.Field()
    """
    This page of organizations.
    """

    total: int = pydantic.Field()
    """
    Total number of organizations the caller belongs to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
