# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Pagination(UniversalBaseModel):
    """
    Pagination metadata for list responses.
    """

    page: int = pydantic.Field()
    """
    Current page number
    """

    limit: int = pydantic.Field()
    """
    Items per page
    """

    total: int = pydantic.Field()
    """
    Total number of items
    """

    total_pages: int = pydantic.Field()
    """
    Total number of pages
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
