# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PayrollAccessSetupStatus(UniversalBaseModel):
    completed: bool = pydantic.Field()
    """
    Whether payroll access setup has been completed for this employer.
    """

    submitted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the setup form was submitted (RFC 3339), or `null` if it has not been submitted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
