# This file was auto-generated by Fern from our API Definition.

import typing

PlanYearEnrollmentElectionStatus = typing.Union[typing.Literal["Enrolled", "Waived", "Pending", "Expired"], typing.Any]
