# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pagination import Pagination
from .plan_year_enrollment import PlanYearEnrollment


class PlanYearEnrollmentListResponse(UniversalBaseModel):
    """
    Paginated list response containing plan year enrollment resources.
    """

    data: typing.List[PlanYearEnrollment] = pydantic.Field()
    """
    This page of plan year enrollments.
    """

    pagination: Pagination = pydantic.Field()
    """
    Page metadata. Request the next page by incrementing `page`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
