# This file was auto-generated by Fern from our API Definition.

import typing

PlanYearEnrollmentPolicyStatus = typing.Union[
    typing.Literal["Coverage Upcoming", "Coverage Effective", "Coverage Ended", "Cancelled"], typing.Any
]
