# This file was auto-generated by Fern from our API Definition.

import typing

ProductCode = typing.Union[
    typing.Literal[
        "EBA",
        "VPC",
        "VPC_CORE",
        "MEC",
        "MEC2",
        "MEC_PLUS",
        "MVP",
        "MVP2",
        "MVPSL",
        "MVPSL2",
        "VD",
        "VV",
        "ICHRA",
        "ICHRA_PREMIUM_PLUS",
        "ICHRA_REIMBURSEMENT_ONLY",
    ],
    typing.Any,
]
