# This file was auto-generated by Fern from our API Definition.

import typing

ResourceType = typing.Union[
    typing.Literal["enrollment", "employee", "employer", "dependent", "plan_year", "payroll_deduction"], typing.Any
]
